"""Initial schema — applies buxoro_taxi_schema.sql (tables, indexes, triggers).

The SQL file is the single source of truth (it also defines the 3 triggers and
the seed rows). Rather than re-declaring everything in Python, this baseline
migration executes that file verbatim. Subsequent schema changes should use
normal autogenerated migrations against the SQLAlchemy models.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-29
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence, Union

from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# repo_root/alembic/versions/this_file.py -> repo_root
_REPO_ROOT = Path(__file__).resolve().parents[2]
_SCHEMA_SQL = _REPO_ROOT / "buxoro_taxi_schema.sql"

_TABLES = [
    "admin_audit_logs",
    "notifications",
    "promo_usages",
    "promo_codes",
    "bonus_achievements",
    "bonus_campaigns",
    "wallet_transactions",
    "wallets",
    "driver_commissions",
    "commission_config",
    "pricing_config",
    "ratings",
    "payments",
    "rides",
    "driver_documents",
    "drivers",
    "users",
]


def _strip_line_comments(sql: str) -> str:
    """Remove ``-- ...`` line comments that sit outside single-quoted strings.

    The source file's comments contain ``%`` (a psycopg placeholder char) and
    ``:lng``/``:lat`` tokens; stripping the comments lets the raw DBAPI execute
    the DDL without misreading them as parameters. No ``--`` appears inside a
    string literal in this schema, so this is safe.
    """
    out_lines: list[str] = []
    for line in sql.splitlines():
        in_quote = False
        cut = None
        i = 0
        while i < len(line):
            ch = line[i]
            if ch == "'":
                in_quote = not in_quote
            elif ch == "-" and not in_quote and line[i : i + 2] == "--":
                cut = i
                break
            i += 1
        out_lines.append(line if cut is None else line[:cut])
    return "\n".join(out_lines)


def upgrade() -> None:
    sql = _strip_line_comments(_SCHEMA_SQL.read_text(encoding="utf-8"))
    # Run via the raw DBAPI connection (multi-statement DDL, incl. plpgsql).
    op.get_bind().exec_driver_sql(sql)


def downgrade() -> None:
    for trg, tbl in [
        ("trg_update_rating", "ratings"),
        ("trg_ride_completion", "rides"),
        ("trg_bonus_achievement", "bonus_achievements"),
    ]:
        op.execute(f"DROP TRIGGER IF EXISTS {trg} ON {tbl}")
    for fn in (
        "update_driver_rating",
        "process_ride_completion",
        "process_bonus_achievement",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {fn}() CASCADE")
    for tbl in _TABLES:
        op.execute(f"DROP TABLE IF EXISTS {tbl} CASCADE")
